<tr>
    <td><a href='<?php echo Zend_Controller_Front::getInstance()->getBaseUrl(); ?>/crop-ws/update/id/<?php echo $this->id;?>'>Edit</a> |
Delete
    </td>
<td><?php echo $this->name; ?></td>
<td><?php echo $this->shelf_life_air; ?></td>
<td><?php echo $this->shelf_life_fridge; ?></td>
<td><?php echo $this->shelf_life_freezer; ?></td>
<td><?php echo $this->date_available; ?></td>
<td><?php echo $this->expected_quantity; ?></td>

</tr>