<html>
    <head>
        <title>AgroLogistics GraphGenerator Test</title>
        <script src="jquery/jquery.min.js" type="text/javascript"></script>
    </head>
    
    <body>
        <form action="<?php echo $this->apiUrl; ?>" method="POST">
            <h1>AgroLogistics GraphGenerator Test</h1>
            
            <textarea id="requestData" name="requestData" rows="10" cols="80">
                {
                    "title": "New Title",
                    "data": [12,235,436,34,34,343],
                    "xAxisTitle": "Weeks",
                    "yAxisTitle": "Production",
                    "width": 600,
                    "height": 200,
                    "chartType": "line"
                }
            </textarea>
            
            <br />
            
            <input type="submit" name="SUBMIT" value="Call Api" />
        </form>
    </body>
</html>